name: Go

on:
  push:
    branches: [ "master" ]      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

# - name: Test
#   run: go test -v ./...

    - name: Build
      run: mkdir builds && GOOS=linux GOARCH=amd64 go build -race -ldflags "-extldflags '-static'" -o build/mwms

    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: build_data
        path: build/

  deploy:
    needs: [build]
    environment: production

    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.DEPLOY_KEY_FOR_VDS}}
      HOSTNAME: ${{secrets.HOSTNAME}}

    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/download-artifact@v3
        with:
          name: build_data
          path: build/

      - name: Prepare key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$SSH_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . $HOSTNAME:/home/mike/deploy_mwms
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $HOSTNAME chmod +x deploy_mwms/build/mwms
