name: Go

on:
  push:
    branches: [ "master" ]      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          cd app && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . mike@194.87.235.12:/home/deploy_mwms
