name: Go

on:
  push:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
      
      
      # Setup key
    - name: Deploy
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "$" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    - run: cd app && rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . mike@194.87.235.12:/home/deploy_mwms
